<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdownlist_Country</name>
   <tag></tag>
   <elementGuidId>f9d02e09-fc7a-44f5-be8e-0a65bdc2539d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name='country_id']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
