<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdownlist_Region</name>
   <tag></tag>
   <elementGuidId>f17b0483-f737-4bca-b2f2-725049496efa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name='region_id']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
