<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_City</name>
   <tag></tag>
   <elementGuidId>8fac18a6-054f-4fad-8fe5-b194a835d4e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name='city']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
