<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_Firstname</name>
   <tag></tag>
   <elementGuidId>6002fb01-e0e5-400d-9e2c-77338c6e3765</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name='firstname']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
