<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_Telephone</name>
   <tag></tag>
   <elementGuidId>544c273e-111b-49cb-9023-c1cca8c9369e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name='telephone']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
