<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_Company</name>
   <tag></tag>
   <elementGuidId>f6980e04-d149-47fa-9dc4-f0bd6dddc17e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name='company']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
