<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_Lastname</name>
   <tag></tag>
   <elementGuidId>79bc78c4-f5ab-474c-aa26-977f7e0bb0aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name='lastname']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
