<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_Street</name>
   <tag></tag>
   <elementGuidId>ea9c666f-6aa9-4499-857e-31c8ca20c97c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name='street[0]']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
