<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_Postcode</name>
   <tag></tag>
   <elementGuidId>d110616e-8b23-410e-bf5b-8ef3b17769d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name='postcode']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
