<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_Cart</name>
   <tag></tag>
   <elementGuidId>2469f3e9-5972-4037-b3b4-4b21abd2373b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.action.showcart</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
