<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>message_Search</name>
   <tag></tag>
   <elementGuidId>4f112326-fa88-4ffa-9c9d-24820c2afd87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.base</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
