<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_All Classes and Interfaces</name>
   <tag></tag>
   <elementGuidId>63b8f1a1-c7b3-4523-a5b0-3e81e68a67e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='class-summary-tab0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#class-summary-tab0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4d0911be-9e31-4fde-874d-374d8d690019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>class-summary-tab0</value>
      <webElementGuid>e5bfa6db-c215-444f-a379-5ab20a655602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>c5e1a759-43e6-428e-8214-b3d2c3d5a4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>10907b01-5011-400d-b4ec-a762e3b38cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>class-summary.tabpanel</value>
      <webElementGuid>1b1819eb-2cfe-48fa-b2e3-f77446950058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3a232ca3-4b26-4b7b-b800-b05cc7b9a9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>switchTab(event)</value>
      <webElementGuid>493945ee-576f-460c-b979-5996e9a6c26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>show('class-summary', 'class-summary', 2)</value>
      <webElementGuid>ac9479e9-19f1-416a-8fd3-571fd475b182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active-table-tab</value>
      <webElementGuid>ab42fb66-0453-43a3-9e4c-8606e8555c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Classes and Interfaces</value>
      <webElementGuid>2dfa0106-b098-4c41-86dd-d36a34ea0779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;class-summary-tab0&quot;)</value>
      <webElementGuid>1cc9db6f-84ab-4c29-b2dd-01882c55bee9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='class-summary-tab0']</value>
      <webElementGuid>621428cd-597a-4883-b30f-76fd3c96eaba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='class-summary']/div/button</value>
      <webElementGuid>13174a4d-9746-4afe-a036-f2cf7c43008c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium'])[2]/following::button[1]</value>
      <webElementGuid>3530246c-8701-4c09-a122-0da398a244ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interfaces'])[1]/preceding::button[1]</value>
      <webElementGuid>e8198d0b-c2a8-4b42-a2cd-ea403f315033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Classes'])[1]/preceding::button[2]</value>
      <webElementGuid>19a23458-2d97-4766-a534-ed275dfded1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All Classes and Interfaces']/parent::*</value>
      <webElementGuid>9de7b38b-885e-46ff-a617-eede87387793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>822af163-f835-48f0-90e1-43e0e17b90b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'class-summary-tab0' and (text() = 'All Classes and Interfaces' or . = 'All Classes and Interfaces')]</value>
      <webElementGuid>f07cce13-7a78-4f20-bfa4-a880f3bb86b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
