<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>button[title='Search']</description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>9e0398d3-0598-43eb-ac6a-27d79c4d6762</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[title='Search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
