<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dashboardtest  TESTAboutSupportChange P_4fefda</name>
   <tag></tag>
   <elementGuidId>62d389d4-41af-4837-b59c-b00cd498e648</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/header/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.oxd-topbar-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f02cebb3-6b08-4037-bed8-fbdce3a2ba13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-topbar-header</value>
      <webElementGuid>fde73031-ab41-466b-bdac-52e33ad5a20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboardtest  TESTAboutSupportChange PasswordLogout</value>
      <webElementGuid>ad5555b2-77da-4781-9ae9-7a518d45d991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-navigation&quot;]/header[@class=&quot;oxd-topbar&quot;]/div[@class=&quot;oxd-topbar-header&quot;]</value>
      <webElementGuid>17e8e615-408b-479b-b1f9-2295b1f0c366</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/header/div</value>
      <webElementGuid>f68f9ecb-d89d-4cbb-8cef-4567fdd920d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div</value>
      <webElementGuid>a8d7e110-d763-4d60-9921-81f22e5c3810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Dashboardtest  TESTAboutSupportChange PasswordLogout' or . = 'Dashboardtest  TESTAboutSupportChange PasswordLogout')]</value>
      <webElementGuid>2a21e8b8-8e04-4127-a95c-be1ec78ed8dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
